### ISSUE TITLE
wordsEn.csv missing

### ISSUE THREAD

**Issue by MareoRaft** [ghseeli/trunconomics#1]
@ghseeli One of our test files calls on the file "wordsEn.csv", but that file is not in the repository (can you add it when you get a chance?).  Preferably there will be a "test_inputs" or similar dedicated folder for files like this.

**Comment by MareoRaft** [comment]
(and after adding the file, update test_truncation.py)

**Comment by MareoRaft** [comment]
The file `basic_test_file.csv` is also missing.

**Comment by MareoRaft** [comment]
Actually, basic_test_file.csv is there.  Perhaps its not hooked up right

**Comment by ghseeli** [comment]
Okay, I have fixed the two issues you described here. Hope that helps! Also, keep in mind, the `test_truncator_tester.py` needs to be run by invoking `pytest`.

**Comment by MareoRaft** [comment]
Thanks!  Are tests passing for you?  My pytest is now hanging (please see if tests are passing on your computer *before* pulling my changes)

**Comment by MareoRaft** [comment]
I think you need to wrap the code in a `def test_some_functionality` function (i'm guessing this is the issue).  Also, please remove the `TODO` if the task is complete.  Thanks!

**Comment by ghseeli** [comment]
The tests as I committed them are all passing for me and run just fine.

**Comment by ghseeli** [comment]
And I didn't remove the TODO statements because I figured you still had to test them.

**Comment by ghseeli** [comment]
But I closed the issue because wordsEn.csv is no longer missing...

**Comment by ghseeli** [comment]
Also, note that `test_truncator.py` is *not* a pytest file. Originally in my naming scheme, that is why it did not end in "test". Confusing, certainly.

**Comment by MareoRaft** [comment]
Ah, so pytest automatically recognizes as test files files that both begin with `test_` and files that end with `_test`.  What is the purpose of the file and what name can we rename it to?

(Also, we can reconfigure pytest if necessary to only recognize one of the two above mentioned indicators, if you think this is more suitable.)

**Comment by MareoRaft** [comment]
Was this the file that you were using to see "how good" a trunctor was?  Perhaps we could call it "truncator evaluator" or similar.

**Comment by ghseeli** [comment]
Yeah, I agree with your assessment. When this file was first made, there were no unit tests. But, it truly is more of an evaluator / method of measuring some stats about a truncation scheme.

**Comment by MareoRaft** [comment]
So I made the following changes:

`truncator_tester` -> `truncator_evaluator` (renamed the module)

`test_truncator_tester` -> `test_truncator_evaluator` (renamed corresponding test file)

`test_truncator` ~~> `main.py` (It seems these functionalities are things we want to run manually on our truncators to see how they are doing.  I have been turning `main.py` into the frontend window for us to run code manually, so I think this is the right place.  Still need more organization within `main.py` though.)

One issue remains: the code still hangs indefinitely.  I will open a new issue for this.
